### ISSUE TITLE
TP6 的问题

### ISSUE THREAD

**Issue by iamssn** [yupoxiong/region#2]
安装 composer require topthink/think-migration  数据库迁移工具

复制vendor/yupoxiong/region/database/migrations/数据库迁移文件到TP迁移目录(一般是根目录下的/database/migrations/)没有这个目录要新建一个 ，然后运行TP自带迁移命令创建表(php think migrate:run) 。

***_region.php 数据库文件种的  引用use think\Db; 换成use think\facade\Db;

**Comment by yupoxiong** [comment]
忘记给新的版本打tag了，已经OK啦
