### ISSUE TITLE
tp6.1.0安装报错

### ISSUE THREAD

**Issue by WeiWenXu4914** [yupoxiong/region#5]
`Fatal error: Uncaught Error: Call to undefined method think\Console::addDefaultCommands() in D:\project\php\common_api\vendor\yupoxiong\region\helper.php:7
Stack trace:
#0 D:\project\php\common_api\vendor\composer\autoload_real.php(41): require()
#1 D:\project\php\common_api\vendor\composer\autoload_real.php(45): ComposerAutoloaderInit0e25d0529ae2d7cf4f8ededd35cf67c0::{closure}('c5578cd1f56f360...', 'D:\\project\\php\\...')
#2 D:\project\php\common_api\vendor\autoload.php(25): ComposerAutoloaderInit0e25d0529ae2d7cf4f8ededd35cf67c0::getLoader()
#3 D:\project\php\common_api\think(7): require('D:\\project\\php\\...')
#4 {main}
  thrown in D:\project\php\common_api\vendor\yupoxiong\region\helper.php on line 7`

**Comment by XFStudy2020** [comment]
终端运行：composer require "yupoxiong/region:1.1.4" 报错，详情如下：
./composer.json has been updated
Running composer update yupoxiong/region
  - Locking yupoxiong/region (v1.1.4)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing yupoxiong/region (v1.1.4): Extracting archive
Generating autoload files
> @php think service:discover
Script @php think service:discover handling the post-autoload-dump event returned with error code 255

请问老师该如何解决？？

**Comment by XFStudy2020** [comment]
这个问题在百度搜了很多类似报错，也一一尝试按别人的方法解决，可是最后都不能解决，好着急！

**Comment by XFStudy2020** [comment]
我的PHP版本7.3.4没问题

**Comment by XFStudy2020** [comment]
TP6.0 和 6.1 都出现一样的问题

**Comment by XFStudy2020** [comment]
处理返回的自动加载后转储事件，错误代码为255

**Comment by yupoxiong** [comment]
已对TP6.1做兼容处理
