### ISSUE TITLE
为何？： v1.1.4在2022.4月那时候对 TP6.0.12 可用，而当下在 TP6.0.1 到 tp6.0.13 却都安装不成功，error code 255

### ISSUE THREAD

**Issue by XFStudy2020** [yupoxiong/region#6]
Script @php think service:discover handling the post-autoload-dump event returned with error code 255

**Comment by XFStudy2020** [comment]
v1.1.4这个版本以后还能继续用吗？

**Comment by XFStudy2020** [comment]
从上周五，到今天，学习使用 yupoxiong/region 这个TP6扩展包，版本是V1.1.4，可总是安装在最后一步报错：Script @php think service:discover handling the post-autoload-dump event returned with error code 255。去看composer.json，发现"require"中也有了"yupoxiong/region": "1.1.4"；尝试 new 一下 \yupoxiong\region\facade\Region 对象，打印也是有这个对象的。可就是运行命令 php think region:migrate 安装数据表，没有任何反应。

**Comment by yupoxiong** [comment]
`composer update`一下就行，正常会自动更新到v1.1.5

**Comment by XFStudy2020** [comment]
我的所有的尝试，都是在已经安装了 “topthink/think-migration:3.0.3” 成功的基础上做的，确实是安装 “yupoxiong/region:1.1.4” 不能成功；那么，yupoxiong/region v1.1.4 目前对 TP6.0 和 TP6.1 都不能用了吗？为何早先2022.4月的时候，对 TP6.0.12 是可用的？这里到底有什么深奥的原因呢？请老师赐教，谢谢！

**Comment by XFStudy2020** [comment]
今天上午再来尝试，直接 composer require yupoxiong/region ，安装成功了，好激动！打开github来看，发现原来老师已经上新v1.1.5. 解决了问题，是一件很激动的事。必须要感谢老师！

**Comment by yupoxiong** [comment]
``> 我的所有的尝试，都是在已经安装了 “topthink/think-migration:3.0.3” 成功的基础上做的，确实是安装 “yupoxiong/region:1.1.4” 不能成功；那么，yupoxiong/region v1.1.4 目前对 TP6.0 和 TP6.1 都不能用了吗？为何早先2022.4月的时候，对 TP6.0.12 是可用的？这里到底有什么深奥的原因呢？请老师赐教，谢谢！

这个扩展之前更新的时候恰好是TP6.0发布不久，当时判断TP版本的时候只是判断了不是在5.0的情况，如果不是6.0，就默认为5.1，在6.1出来之后就会报你发的那个错误，我只是把判断的地方改了一下，具体可以查看commit记录，例如helper.php文件内第6行的判断改成了
```
        if (strpos(\think\App::VERSION, '5.1') === 0) {
```
另外一个问题的解答，之前安装成功的也能使用，主要功能没有做过改动，不过还是建议升级一下。

**Comment by XFStudy2020** [comment]
现在已经可以安装最新的v1.1.5.可是有点纳闷的是：在2022.4月，v1.1.4对TP6.0.12是可以用的（视频课老师的屏幕显示2022.4.16日，视频课的老师安装composer require “topthink/think-migration:3.0.3”和composer require “yupoxiong/region:1.1.4”，运行php think region:migrate，都成功），而目前这几天，我对 TP6.0.1到 TP6.0.12 和 TP6.1 都不能安装“yupoxiong/region:1.1.4”成功，既然已经花了好几天，就非常想知道，这里面存在什么深奥的原因，老师能告知一二吗？致敬！！
&nbsp;


丹枫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月22日(星期一) 下午2:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yupoxiong/region] 为何？： v1.1.4在2022.4月那时候对 TP6.0.12 可用，而当下在 TP6.0.1 到 tp6.0.13 却都安装不成功，error code 255 (Issue #6)





 
Closed #6 as completed.

**Comment by yupoxiong** [comment]
> 现在已经可以安装最新的v1.1.5.可是有点纳闷的是：在2022.4月，v1.1.4对TP6.0.12是可以用的（视频课老师的屏幕显示2022.4.16日，视频课的老师安装composer require “topthink/think-migration:3.0.3”和composer require “yupoxiong/region:1.1.4”，运行php think region:migrate，都成功），而目前这几天，我对 TP6.0.1到 TP6.0.12 和 TP6.1 都不能安装“yupoxiong/region:1.1.4”成功，既然已经花了好几天，就非常想知道，这里面存在什么深奥的原因，老师能告知一二吗？致敬！！ &nbsp; 丹枫 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年5月22日(星期一) 下午2:26 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [yupoxiong/region] 为何？： v1.1.4在2022.4月那时候对 TP6.0.12 可用，而当下在 TP6.0.1 到 tp6.0.13 却都安装不成功，error code 255 (Issue #6) Closed #6 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

参考我的上条回复，原因倒是不深奥，就是看你能不能看懂解释，如果看不懂的话你发个qq我加你吧，给你截图也许能理解。

**Comment by XFStudy2020** [comment]
非常感谢老师，我的QQ: 2512801568，感谢老师赐教！
&nbsp;


丹枫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月22日(星期一) 下午2:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yupoxiong/region] 为何？： v1.1.4在2022.4月那时候对 TP6.0.12 可用，而当下在 TP6.0.1 到 tp6.0.13 却都安装不成功，error code 255 (Issue #6)





  
现在已经可以安装最新的v1.1.5.可是有点纳闷的是：在2022.4月，v1.1.4对TP6.0.12是可以用的（视频课老师的屏幕显示2022.4.16日，视频课的老师安装composer require “topthink/think-migration:3.0.3”和composer require “yupoxiong/region:1.1.4”，运行php think region:migrate，都成功），而目前这几天，我对 TP6.0.1到 TP6.0.12 和 TP6.1 都不能安装“yupoxiong/region:1.1.4”成功，既然已经花了好几天，就非常想知道，这里面存在什么深奥的原因，老师能告知一二吗？致敬！！ &nbsp; 丹枫 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年5月22日(星期一) 下午2:26 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yupoxiong/region] 为何？： v1.1.4在2022.4月那时候对 TP6.0.12 可用，而当下在 TP6.0.1 到 tp6.0.13 却都安装不成功，error code 255 (Issue #6) Closed #6 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
参考我的上条回复，原因倒是不深奥，就是看你能不能看懂解释，如果看不懂的话你发个qq我加你吧，给你截图也许能理解。
